hwi_oauth:
    firewall_names: [main]

    resource_owners:
        google:
            type: google
            client_id: '%google_oauth_client_id%'
            client_secret: '%google_oauth_client_secret%'
            scope: "email profile"